### ISSUE TITLE
Compile Failure (invalid conversion from 'const unsigned char*' to 'const char*)

### ISSUE THREAD

**Issue by Kippykip** [bmx-ng/net.mod#2]
Fails to compile with this error message:
`C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/net.mod/libssh2.mod/glue.cpp:142:21: error: invalid conversion from 'const unsigned char*' to 'const char*' [-fpermissive]
   bbStringFromBytes((const unsigned char *)instruction, instruction_len), _prompts, _responses);`

Here's a larger version of the console
[temp.txt](https://github.com/bmx-ng/net.mod/files/7832446/temp.txt)
`[ 53%] Compiling:version_features.c
[ 53%] Compiling:x509.c
[ 54%] Compiling:x509_crl.c
C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/net.mod/libssh2.mod/glue.cpp: In function 'void _interactive_callback(const char*, int, const char*, int, int, const LIBSSH2_USERAUTH_KBDINT_PROMPT*, LIBSSH2_USERAUTH_KBDINT_RESPONSE*, void**)':
C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/net.mod/libssh2.mod/glue.cpp:141:96: error: invalid conversion from 'const unsigned char*' to 'const char*' [-fpermissive]
  net_libssh2_TSSHSession__kbdCallback(((MaxSSHSession*)*abstract)->Handle(), bbStringFromBytes((const unsigned char *)name, name_len),
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/brl.mod/blitz.mod/blitz.h:37,
                 from C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/net.mod/libssh2.mod/glue.cpp:34:
C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/brl.mod/blitz.mod/blitz_string.h:36:42: note:   initializing argument 1 of 'BBString* bbStringFromBytes(const char*, int)'
 BBString* bbStringFromBytes( const char *p,int n );
                              ~~~~~~~~~~~~^
C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/net.mod/libssh2.mod/glue.cpp:142:21: error: invalid conversion from 'const unsigned char*' to 'const char*' [-fpermissive]
   bbStringFromBytes((const unsigned char *)instruction, instruction_len), _prompts, _responses);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/brl.mod/blitz.mod/blitz.h:37,
                 from C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/net.mod/libssh2.mod/glue.cpp:34:
C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/brl.mod/blitz.mod/blitz_string.h:36:42: note:   initializing argument 1 of 'BBString* bbStringFromBytes(const char*, int)'
 BBString* bbStringFromBytes( const char *p,int n );
                              ~~~~~~~~~~~~^
[ 54%] Compiling:x509_crt.c
Build Error: failed to compile (1) C:/BlitzMax/BlitzMax_win32_x86_0.129.3.45/BlitzMax/mod/net.mod/libssh2.mod/glue.cpp
Process complete
`

**Comment by GWRon** [comment]
It might just need the same little cast as other modules needed too.

**Comment by woollybah** [comment]
Should be fixed.
