### ISSUE TITLE
libcurl unable to compile due to latest BCC changes.

### ISSUE THREAD

**Issue by thareh** [bmx-ng/net.mod#6]
Hey,

I get this error when trying to compile libcurl using latest BCC:
`Build Error: failed to compile (-1073741819) D:/Programs/BlitzMax/mod/net.mod/libcurl.mod/curlmain.bmx`

Also, you need to import aesni in mbedtls.mod per #3 or it will not compile as well.

Thanks,
-- Thareh

**Comment by woollybah** [comment]
Resolved with https://github.com/bmx-ng/bcc/commit/3943b49611905b0223152a9dcdc51d8ee9ae6491
